---
title: "Merge conflicts"
subtitle: "Application exercise 06"
author: "Mine Cetinkaya-Rundel"
date: "2018-09-18"
output: 
  html_document: 
    fig_height: 4
    fig_width: 10
---

1. Clone your assignment repo in RStudio Cloud (`ae-06-merge-conflicts-TEAMNAME`), 
and open the R Markdown file.
2. Assign the numbers 1, 2, 3, and 4 to each of the team members.
3. Take turns in completing the exercise, only one member at a time:
  - Member 1: Change the team name to your team name, knit, commit, push.
  - Member 2: Change the team name to something else, knit, commit, push. You 
  will get an error. Pull. Review the document with the merge conflict. Resolve 
  the conflict with the preferred change. Commit and push.
  - Member 3: Create a plot displaying the relationship between price and carat, 
  controlling for cut of the diamonds (see next slide for the plot). Knit, 
  commit, push. You will get an error, read it, and pull. No merge conflicts 
  should occur. Now push.
  - Member 4: Set the alpha level to 0.5. Knit, commit, push. You will get an 
  error. Pull. Review the document with the merge conflict. Clear the merge 
  conflict by choosing the correct/preferred change. Commit, and push.
4. All members: Pull, and observe the changes in your document.
